manifest:
  remotes:
    - name: refil
      url-base: https://github.com/refil
    - name: Greg-T8
      url-base: https://github.com/Greg-T8/zmk
  projects:
    - name: zmk
      remote: Greg-T8
      path: zmk
      revision: main
      import: app/west.yml
  self:
    path: config