manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk1
      repo-path: zmk
      remote: urob
      path: zmk
      revision: main
      import: app/west.yml
  self:
    path: config